# Simulation

- In this lesson, we will work through several examples of using random numbers to simulate real-world scenarios.
- For reference, the [viz module](./viz.py) contains the visuals used for these lessons.

## Generating Random Numbers with Numpy

The `numpy.random` module provides a number of functions for generating random numbers.

- `np.random.choice`: selects random options from a list
- `np.random.uniform`: generates numbers between a given lower and upper bound
- `np.random.random`: generates numbers between 0 and 1
- `np.random.randn`: generates numbers from the standard normal distribution
- `np.random.normal`: generates numbers from a normal distribution with a specified mean and standard deviation

## How to run simulations with numpy/python/pandas

### Process
1. Represent the data
2. Create a matrix of random numbers
3. Apply an aggregate row-wise to produce the results of each simulation
4. Aggregate the resulting data to get our experimental probability

In [30]:
import numpy as np
import pandas as pd

In [15]:
#say I'm creating simulated die rolls:
# we'll probably need to do that for the big question right after this
outcomes = [1,2,3,4,5,6]
n_trials = 10000 # this is just a random number that I'm picking, larger is better generally
tenk_dierolls = np.random.choice(outcomes, n_trials)

In [10]:
hundred_dierolls[:10]

array([5, 6, 1, 6, 4, 2, 5, 5, 1, 3])

## What's the probaility of rolling a 2 on a 6-sided die?

In [16]:
(tenk_dierolls == 2).sum()/len(hundred_dierolls)

16.4

- What is the expected probability?

### 1. - 2. Represent the data, Create a matrix of appropriate random numbers


### 3. Apply an aggregate row-wise to produce the results of each simulation

### 4. Aggregate the resulting data to get our experimental probability

### Expected Probability

### Consolidate & increase trial size

# YAY Completed simulation!

- Also known as the monte carlo method

## What is the probability that we roll 5 or greater on a die roll? 

In [17]:
#on paper this is 1/6 + 1/6 == 1/3 == 0.333333333333333333
tenk_dierolls[:5]

array([4, 2, 2, 6, 5])

In [18]:
(tenk_dierolls > 4).mean()

0.3249

### Expected?

### Simulate!

## What's the probability of getting 2 or more heads after flipping 3 coins?

### 1. Represent the data

In [31]:
# lets create our simulation:
# define our outcomes:
outcomes = ['H', 'T']
# number of trials will be our columns
n_trials = 3
# picking a number for our simulations.
# the higher the better, but too high may cause the computer
# to run a bit longer than we would like
n_simulations = 10_000

In [32]:
# define our simulation
# create three coin flips(columns) across 10k rows(simulations of the 3 coin flips)
three_flips = np.random.choice(outcomes, (n_simulations, n_trials)) #rows by columns
three_flips

array([['T', 'T', 'T'],
       ['H', 'H', 'T'],
       ['T', 'T', 'T'],
       ...,
       ['T', 'T', 'H'],
       ['T', 'H', 'H'],
       ['H', 'T', 'T']], dtype='<U1')

### 2. Create a matrix of random numbers

In [ ]:
# remember dimensions on np array shapes 
# rows, columns
three_flips = 

- Here the `(10_000, 3)` tuple tells numpy the shape of the matrix to generate. 
- Since we are flipping 3 coins we have 3 columns, and we are doing 10_000 simulations, we'll have 20 rows.

### 3. Apply an aggregate row-wise to produce the results of each simulation

In [35]:
# axes: 0: r0ws, 1: co1s
#set up a bool for all the times we hit heads on a coin
#get the sum across everysimulations(sum across columns which is why we choose axis 1)
#now that we have the sum across columns, we can get the times it is greater than 1 and take the average of that 
# boolean value
((three_flips == 'H').sum(axis=1) >=2).mean()

0.5015

- Count how many heads there are for each simlution

- this 1-d array shows how many heads appeared in each simulations
- we want to know how many times we have 2 or more heads, so lets convert that to a boolean array when our head count is 2 or greater

### 4. Aggregate the resulting data to get our experimental probability
- Here we'll calculate the number of successful trials 

### Consolidate & increase simulations!

## Carnival Dice Rolls

> You are at a carnival and come across a person in a booth offering you a game
> of "chance" (as people in booths at carnivals tend to do).

> You pay 5 dollars and roll 3 dice. If the sum of the dice rolls is greater
> than 12, you get 15 dollars. If it's less than or equal to 12, you get
> nothing.

> Assuming the dice are fair, should you play this game? How would this change
> if the winning condition was a sum greater than *or equal to* 12?

To simulate this problem, we'll write the python code to simulate the scenario described above, then repeat it a large amount of times.

### 1. represent our data

In [36]:
# number of times we want to repeat this experiment
n_simulations = 10_000
# number of times we roll the dice
# the number of columns in our matrix
n_trials = 3
# outcomes, the list of possible options of things that could happen
# in the scope of a die roll
outcomes = [1,2,3,4,5,6]


### 2. set up matrix of random numbers

In [37]:
dice_game = np.random.choice(outcomes, (n_simulations, n_trials))

In [38]:
dice_game[:15]

array([[5, 2, 5],
       [5, 3, 1],
       [1, 1, 4],
       [3, 4, 6],
       [6, 5, 1],
       [2, 3, 5],
       [1, 2, 2],
       [6, 3, 5],
       [3, 6, 1],
       [3, 4, 6],
       [3, 4, 1],
       [6, 6, 3],
       [3, 1, 2],
       [6, 6, 3],
       [6, 1, 3]])

### 3. apply an aggregate row-wise to produce the results of each simulation

In [41]:
# sum the three trials together
(dice_game.sum(axis =1) > 12).mean()

0.2602

#### Find which simulations "won"

In [44]:
# dice game, summed across three trials]
#  checking to see if that sum is greater than 12
# and then taking the sum of all of those 100k simulations
#costs $5 to play gain $15 when win
cost_of_game = 5
winnings = 15
winning_odds = (dice_game.sum(axis =1) > 12).mean()
gross = winning_odds * winnings
gross > cost_of_game

False

### 4. aggregate the resulting data to get our experimental probability

### To complete this problem, we can calculate the expected profit from our win rate:

In [ ]:
# playing the game costs $5
# winning the game gets $15


In [ ]:
# flat cost to play the game is $5.00
# which means on average playing this game, you would lose


If our win condition changes to the sum being greater than or equal to 12, then, based on our simulations, on average, we expect to win about 60 cents

In [46]:
cost_of_game = 5
winnings = 15
winning_odds = (dice_game.sum(axis =1) >= 12).mean()
gross = winning_odds * winnings
gross > cost_of_game
gross

5.688

## No Rest or Relaxation

> There's a 30% chance my son takes a nap on any given weekend day. What is the chance that he takes a nap at least one day this weekend? What is the probability that he doesn't nap at all?

### 1. represent our data

In [47]:
# the probability of napping is 30%
p_nap = 0.3
# number of trials is equivalent to the number of days in the weekend
n_days = n_trials = 2
# the number of simulations is just a big number that we are choose
# in order to approximate the theoretical value
n_simulations = 100_000

### 2. set up matrix of random numbers

To determine whether or not a nap is taken on a given day, we'll generate a random number between 0 and 1, and say that it is a nap if it is less than our probability of taking a nap.

In [53]:
nap_sims = np.random.random((n_simulations, n_days))

In [54]:
# lets look at the first few rows:
nap_sims[:15]

array([[0.15049677, 0.75164292],
       [0.67754033, 0.07462369],
       [0.48631156, 0.52148931],
       [0.91791278, 0.30179135],
       [0.56782549, 0.1464622 ],
       [0.5603362 , 0.21247958],
       [0.12835629, 0.52391468],
       [0.4356471 , 0.06857516],
       [0.70950591, 0.91947764],
       [0.70037942, 0.29510265],
       [0.75590481, 0.64334457],
       [0.42155443, 0.05029845],
       [0.18216904, 0.35621821],
       [0.46935876, 0.38276764],
       [0.31375013, 0.37030344]])

### 3. apply an aggregate row-wise to produce the results of each simulation

In [55]:
# we compare these decimals to the probability of napping
# because our generated numbers are between 0 and 1 and are decimals,
# we know that we have approximately 30% odds
# of that number hitting between 0.00 and 0.30
# so the times that our generated number
# is less than our prob of nap,
# represents a successful nap in this situation
nap_wins = (nap_sims < p_nap)

In [56]:
nap_wins

array([[ True, False],
       [False,  True],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [ True, False]])

In [57]:
((nap_wins).sum(axis=1) > 0).mean()

0.5063

In [62]:
((nap_wins).sum(axis=1) == 0).mean()\
+\
((nap_wins).sum(axis=1) == 1).mean()\
+\
((nap_wins).sum(axis=1) == 2).mean()

1.0

Now that we have each day as either true or false, we can take the sum of each row to find the total number of naps for the weekend. When we sum an array of boolean values, numpy will treat `True` as 1 and `False` as 0.

Now we have the results of our simulation, an array where each number in the array represents how many naps were taken in a two day weekend.

### 4. aggregate the resulting data to get our experimental probability

We can use this to answer our original questions, what is the probability that at least one nap is taken?

What is the probability no naps are taken?

In [63]:
((nap_wins).sum(axis=1) == 0).mean()

0.4937

## One With Dataframes

Let's take a look at one more problem:

> What is the probability of getting at least one 3 in 3 dice rolls?

To simulate this, we'll use a similar strategy to how we modeled the dice rolls in the previous example, but this time, we'll store the results in a pandas dataframe so that we can apply a lambda function that will check to see if one of the rolls was a 3.

### 1. represent our data

In [74]:
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 100_000
n_rolls = n_trials = 3

### 2. set up matrix of random numbers

In [75]:
rolls = np.random.choice(outcomes, (n_simulations, n_trials))

### store results in dataframe!

In [76]:
import pandas as pd
roll_df = pd.DataFrame(rolls)

In [81]:
df.assign(rolled_three) (roll_df == 3).sum(axis=1) >0)
roll_df

0  1  2
0      4  2  6
1      5  4  6
2      1  3  1
3      3  2  6
4      3  5  4
...   .. .. ..
99995  1  2  3
99996  3  2  5
99997  3  3  4
99998  6  3  5
99999  3  2  5

[100000 rows x 3 columns]

In [ ]:
times_we_roll3= 

In [ ]:
roll_df.rolled_three

In [ ]:
roll_df.rolled_three.mean()

### 3. apply an aggregate row-wise to produce the results of each simulation

In [70]:
# find the circumstance where the die roll is equal to 3, sum
# the boolean ints (0==False, 1 == True) across the columns (axis=1)times_we_rolled_three = (roll_df == 3).sum(axis=1)

### 4. aggregate the resulting data to get our experimental probability

In [ ]:
# the average of the times where we got at least one three
(times_we_rolled_three > 0).mean()